-- CreateEnum
CREATE TYPE "CHANNEL_BLACK_LIST_TYPE" AS ENUM ('BLACKLIST', 'WHITELIST');

-- AlterTable
ALTER TABLE "Channel" ADD COLUMN     "type" "CHANNEL_BLACK_LIST_TYPE" NOT NULL DEFAULT 'BLACKLIST';
